//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizAttendance.Maintenance {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string studNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string studNum {
            get {
                return this.studNumField;
            }
            set {
                if ((object.ReferenceEquals(this.studNumField, value) != true)) {
                    this.studNumField = value;
                    this.RaisePropertyChanged("studNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Class : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yearNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string termNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string roomName {
            get {
                return this.roomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.roomNameField, value) != true)) {
                    this.roomNameField = value;
                    this.RaisePropertyChanged("roomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string subName {
            get {
                return this.subNameField;
            }
            set {
                if ((object.ReferenceEquals(this.subNameField, value) != true)) {
                    this.subNameField = value;
                    this.RaisePropertyChanged("subName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sectName {
            get {
                return this.sectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sectNameField, value) != true)) {
                    this.sectNameField = value;
                    this.RaisePropertyChanged("sectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string yearName {
            get {
                return this.yearNameField;
            }
            set {
                if ((object.ReferenceEquals(this.yearNameField, value) != true)) {
                    this.yearNameField = value;
                    this.RaisePropertyChanged("yearName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string termName {
            get {
                return this.termNameField;
            }
            set {
                if ((object.ReferenceEquals(this.termNameField, value) != true)) {
                    this.termNameField = value;
                    this.RaisePropertyChanged("termName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.startTimeField, value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.endTimeField, value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Maintenance.MaintenanceSoap")]
    public interface MaintenanceSoap {
        
        // CODEGEN: Generating message contract since element name GetSchoolYearsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolYears", ReplyAction="*")]
        QuizAttendance.Maintenance.GetSchoolYearsResponse GetSchoolYears(QuizAttendance.Maintenance.GetSchoolYearsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolYears", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSchoolYearsResponse> GetSchoolYearsAsync(QuizAttendance.Maintenance.GetSchoolYearsRequest request);
        
        // CODEGEN: Generating message contract since element name GetSectionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSections", ReplyAction="*")]
        QuizAttendance.Maintenance.GetSectionsResponse GetSections(QuizAttendance.Maintenance.GetSectionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSections", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSectionsResponse> GetSectionsAsync(QuizAttendance.Maintenance.GetSectionsRequest request);
        
        // CODEGEN: Generating message contract since element name GetRoomsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRooms", ReplyAction="*")]
        QuizAttendance.Maintenance.GetRoomsResponse GetRooms(QuizAttendance.Maintenance.GetRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetRoomsResponse> GetRoomsAsync(QuizAttendance.Maintenance.GetRoomsRequest request);
        
        // CODEGEN: Generating message contract since element name GetSubjectsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubjects", ReplyAction="*")]
        QuizAttendance.Maintenance.GetSubjectsResponse GetSubjects(QuizAttendance.Maintenance.GetSubjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubjects", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSubjectsResponse> GetSubjectsAsync(QuizAttendance.Maintenance.GetSubjectsRequest request);
        
        // CODEGEN: Generating message contract since element name GetStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        QuizAttendance.Maintenance.GetStudentsResponse GetStudents(QuizAttendance.Maintenance.GetStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetStudentsResponse> GetStudentsAsync(QuizAttendance.Maintenance.GetStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name SY from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSchoolYear", ReplyAction="*")]
        QuizAttendance.Maintenance.InsertSchoolYearResponse InsertSchoolYear(QuizAttendance.Maintenance.InsertSchoolYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSchoolYear", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSchoolYearResponse> InsertSchoolYearAsync(QuizAttendance.Maintenance.InsertSchoolYearRequest request);
        
        // CODEGEN: Generating message contract since element name R from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRoom", ReplyAction="*")]
        QuizAttendance.Maintenance.InsertRoomResponse InsertRoom(QuizAttendance.Maintenance.InsertRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertRoomResponse> InsertRoomAsync(QuizAttendance.Maintenance.InsertRoomRequest request);
        
        // CODEGEN: Generating message contract since element name Sec from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSection", ReplyAction="*")]
        QuizAttendance.Maintenance.InsertSectionResponse InsertSection(QuizAttendance.Maintenance.InsertSectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSection", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSectionResponse> InsertSectionAsync(QuizAttendance.Maintenance.InsertSectionRequest request);
        
        // CODEGEN: Generating message contract since element name Sub from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSubject", ReplyAction="*")]
        QuizAttendance.Maintenance.InsertSubjectResponse InsertSubject(QuizAttendance.Maintenance.InsertSubjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSubjectResponse> InsertSubjectAsync(QuizAttendance.Maintenance.InsertSubjectRequest request);
        
        // CODEGEN: Generating message contract since element name LName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStudent", ReplyAction="*")]
        QuizAttendance.Maintenance.InsertStudentResponse InsertStudent(QuizAttendance.Maintenance.InsertStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertStudentResponse> InsertStudentAsync(QuizAttendance.Maintenance.InsertStudentRequest request);
        
        // CODEGEN: Generating message contract since element name Sub from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSubject", ReplyAction="*")]
        QuizAttendance.Maintenance.DeleteSubjectResponse DeleteSubject(QuizAttendance.Maintenance.DeleteSubjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSubjectResponse> DeleteSubjectAsync(QuizAttendance.Maintenance.DeleteSubjectRequest request);
        
        // CODEGEN: Generating message contract since element name Sec from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSection", ReplyAction="*")]
        QuizAttendance.Maintenance.DeleteSectionResponse DeleteSection(QuizAttendance.Maintenance.DeleteSectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSection", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSectionResponse> DeleteSectionAsync(QuizAttendance.Maintenance.DeleteSectionRequest request);
        
        // CODEGEN: Generating message contract since element name R from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoom", ReplyAction="*")]
        QuizAttendance.Maintenance.DeleteRoomResponse DeleteRoom(QuizAttendance.Maintenance.DeleteRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteRoomResponse> DeleteRoomAsync(QuizAttendance.Maintenance.DeleteRoomRequest request);
        
        // CODEGEN: Generating message contract since element name SY from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSchoolYear", ReplyAction="*")]
        QuizAttendance.Maintenance.DeleteSchoolYearResponse DeleteSchoolYear(QuizAttendance.Maintenance.DeleteSchoolYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSchoolYear", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSchoolYearResponse> DeleteSchoolYearAsync(QuizAttendance.Maintenance.DeleteSchoolYearRequest request);
        
        // CODEGEN: Generating message contract since element name GetClassRecordResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClassRecord", ReplyAction="*")]
        QuizAttendance.Maintenance.GetClassRecordResponse GetClassRecord(QuizAttendance.Maintenance.GetClassRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClassRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetClassRecordResponse> GetClassRecordAsync(QuizAttendance.Maintenance.GetClassRecordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolYearsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolYears", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetSchoolYearsRequestBody Body;
        
        public GetSchoolYearsRequest() {
        }
        
        public GetSchoolYearsRequest(QuizAttendance.Maintenance.GetSchoolYearsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSchoolYearsRequestBody {
        
        public GetSchoolYearsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchoolYearsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchoolYearsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetSchoolYearsResponseBody Body;
        
        public GetSchoolYearsResponse() {
        }
        
        public GetSchoolYearsResponse(QuizAttendance.Maintenance.GetSchoolYearsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchoolYearsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuizAttendance.Maintenance.ArrayOfString GetSchoolYearsResult;
        
        public GetSchoolYearsResponseBody() {
        }
        
        public GetSchoolYearsResponseBody(QuizAttendance.Maintenance.ArrayOfString GetSchoolYearsResult) {
            this.GetSchoolYearsResult = GetSchoolYearsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSectionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSections", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetSectionsRequestBody Body;
        
        public GetSectionsRequest() {
        }
        
        public GetSectionsRequest(QuizAttendance.Maintenance.GetSectionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSectionsRequestBody {
        
        public GetSectionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSectionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSectionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetSectionsResponseBody Body;
        
        public GetSectionsResponse() {
        }
        
        public GetSectionsResponse(QuizAttendance.Maintenance.GetSectionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSectionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuizAttendance.Maintenance.ArrayOfString GetSectionsResult;
        
        public GetSectionsResponseBody() {
        }
        
        public GetSectionsResponseBody(QuizAttendance.Maintenance.ArrayOfString GetSectionsResult) {
            this.GetSectionsResult = GetSectionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRooms", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetRoomsRequestBody Body;
        
        public GetRoomsRequest() {
        }
        
        public GetRoomsRequest(QuizAttendance.Maintenance.GetRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRoomsRequestBody {
        
        public GetRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetRoomsResponseBody Body;
        
        public GetRoomsResponse() {
        }
        
        public GetRoomsResponse(QuizAttendance.Maintenance.GetRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuizAttendance.Maintenance.ArrayOfString GetRoomsResult;
        
        public GetRoomsResponseBody() {
        }
        
        public GetRoomsResponseBody(QuizAttendance.Maintenance.ArrayOfString GetRoomsResult) {
            this.GetRoomsResult = GetRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubjects", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetSubjectsRequestBody Body;
        
        public GetSubjectsRequest() {
        }
        
        public GetSubjectsRequest(QuizAttendance.Maintenance.GetSubjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSubjectsRequestBody {
        
        public GetSubjectsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubjectsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetSubjectsResponseBody Body;
        
        public GetSubjectsResponse() {
        }
        
        public GetSubjectsResponse(QuizAttendance.Maintenance.GetSubjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuizAttendance.Maintenance.ArrayOfString GetSubjectsResult;
        
        public GetSubjectsResponseBody() {
        }
        
        public GetSubjectsResponseBody(QuizAttendance.Maintenance.ArrayOfString GetSubjectsResult) {
            this.GetSubjectsResult = GetSubjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudents", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetStudentsRequestBody Body;
        
        public GetStudentsRequest() {
        }
        
        public GetStudentsRequest(QuizAttendance.Maintenance.GetStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStudentsRequestBody {
        
        public GetStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetStudentsResponseBody Body;
        
        public GetStudentsResponse() {
        }
        
        public GetStudentsResponse(QuizAttendance.Maintenance.GetStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuizAttendance.Maintenance.Student[] GetStudentsResult;
        
        public GetStudentsResponseBody() {
        }
        
        public GetStudentsResponseBody(QuizAttendance.Maintenance.Student[] GetStudentsResult) {
            this.GetStudentsResult = GetStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSchoolYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSchoolYear", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertSchoolYearRequestBody Body;
        
        public InsertSchoolYearRequest() {
        }
        
        public InsertSchoolYearRequest(QuizAttendance.Maintenance.InsertSchoolYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSchoolYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SY;
        
        public InsertSchoolYearRequestBody() {
        }
        
        public InsertSchoolYearRequestBody(string SY) {
            this.SY = SY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSchoolYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSchoolYearResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertSchoolYearResponseBody Body;
        
        public InsertSchoolYearResponse() {
        }
        
        public InsertSchoolYearResponse(QuizAttendance.Maintenance.InsertSchoolYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertSchoolYearResponseBody {
        
        public InsertSchoolYearResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRoom", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertRoomRequestBody Body;
        
        public InsertRoomRequest() {
        }
        
        public InsertRoomRequest(QuizAttendance.Maintenance.InsertRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string R;
        
        public InsertRoomRequestBody() {
        }
        
        public InsertRoomRequestBody(string R) {
            this.R = R;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertRoomResponseBody Body;
        
        public InsertRoomResponse() {
        }
        
        public InsertRoomResponse(QuizAttendance.Maintenance.InsertRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertRoomResponseBody {
        
        public InsertRoomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSection", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertSectionRequestBody Body;
        
        public InsertSectionRequest() {
        }
        
        public InsertSectionRequest(QuizAttendance.Maintenance.InsertSectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sec;
        
        public InsertSectionRequestBody() {
        }
        
        public InsertSectionRequestBody(string Sec) {
            this.Sec = Sec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertSectionResponseBody Body;
        
        public InsertSectionResponse() {
        }
        
        public InsertSectionResponse(QuizAttendance.Maintenance.InsertSectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertSectionResponseBody {
        
        public InsertSectionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSubjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSubject", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertSubjectRequestBody Body;
        
        public InsertSubjectRequest() {
        }
        
        public InsertSubjectRequest(QuizAttendance.Maintenance.InsertSubjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSubjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sub;
        
        public InsertSubjectRequestBody() {
        }
        
        public InsertSubjectRequestBody(string Sub) {
            this.Sub = Sub;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSubjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSubjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertSubjectResponseBody Body;
        
        public InsertSubjectResponse() {
        }
        
        public InsertSubjectResponse(QuizAttendance.Maintenance.InsertSubjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertSubjectResponseBody {
        
        public InsertSubjectResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStudent", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertStudentRequestBody Body;
        
        public InsertStudentRequest() {
        }
        
        public InsertStudentRequest(QuizAttendance.Maintenance.InsertStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MInitial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StudNum;
        
        public InsertStudentRequestBody() {
        }
        
        public InsertStudentRequestBody(string LName, string GName, string MInitial, string StudNum) {
            this.LName = LName;
            this.GName = GName;
            this.MInitial = MInitial;
            this.StudNum = StudNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.InsertStudentResponseBody Body;
        
        public InsertStudentResponse() {
        }
        
        public InsertStudentResponse(QuizAttendance.Maintenance.InsertStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertStudentResponseBody {
        
        public InsertStudentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSubjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSubject", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteSubjectRequestBody Body;
        
        public DeleteSubjectRequest() {
        }
        
        public DeleteSubjectRequest(QuizAttendance.Maintenance.DeleteSubjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSubjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sub;
        
        public DeleteSubjectRequestBody() {
        }
        
        public DeleteSubjectRequestBody(string Sub) {
            this.Sub = Sub;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSubjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSubjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteSubjectResponseBody Body;
        
        public DeleteSubjectResponse() {
        }
        
        public DeleteSubjectResponse(QuizAttendance.Maintenance.DeleteSubjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteSubjectResponseBody {
        
        public DeleteSubjectResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSection", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteSectionRequestBody Body;
        
        public DeleteSectionRequest() {
        }
        
        public DeleteSectionRequest(QuizAttendance.Maintenance.DeleteSectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Sec;
        
        public DeleteSectionRequestBody() {
        }
        
        public DeleteSectionRequestBody(string Sec) {
            this.Sec = Sec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteSectionResponseBody Body;
        
        public DeleteSectionResponse() {
        }
        
        public DeleteSectionResponse(QuizAttendance.Maintenance.DeleteSectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteSectionResponseBody {
        
        public DeleteSectionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRoom", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteRoomRequestBody Body;
        
        public DeleteRoomRequest() {
        }
        
        public DeleteRoomRequest(QuizAttendance.Maintenance.DeleteRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string R;
        
        public DeleteRoomRequestBody() {
        }
        
        public DeleteRoomRequestBody(string R) {
            this.R = R;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteRoomResponseBody Body;
        
        public DeleteRoomResponse() {
        }
        
        public DeleteRoomResponse(QuizAttendance.Maintenance.DeleteRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteRoomResponseBody {
        
        public DeleteRoomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSchoolYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSchoolYear", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteSchoolYearRequestBody Body;
        
        public DeleteSchoolYearRequest() {
        }
        
        public DeleteSchoolYearRequest(QuizAttendance.Maintenance.DeleteSchoolYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSchoolYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SY;
        
        public DeleteSchoolYearRequestBody() {
        }
        
        public DeleteSchoolYearRequestBody(string SY) {
            this.SY = SY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSchoolYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSchoolYearResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.DeleteSchoolYearResponseBody Body;
        
        public DeleteSchoolYearResponse() {
        }
        
        public DeleteSchoolYearResponse(QuizAttendance.Maintenance.DeleteSchoolYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteSchoolYearResponseBody {
        
        public DeleteSchoolYearResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClassRecord", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetClassRecordRequestBody Body;
        
        public GetClassRecordRequest() {
        }
        
        public GetClassRecordRequest(QuizAttendance.Maintenance.GetClassRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClassRecordRequestBody {
        
        public GetClassRecordRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClassRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClassRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuizAttendance.Maintenance.GetClassRecordResponseBody Body;
        
        public GetClassRecordResponse() {
        }
        
        public GetClassRecordResponse(QuizAttendance.Maintenance.GetClassRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClassRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuizAttendance.Maintenance.Class[] GetClassRecordResult;
        
        public GetClassRecordResponseBody() {
        }
        
        public GetClassRecordResponseBody(QuizAttendance.Maintenance.Class[] GetClassRecordResult) {
            this.GetClassRecordResult = GetClassRecordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaintenanceSoapChannel : QuizAttendance.Maintenance.MaintenanceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaintenanceSoapClient : System.ServiceModel.ClientBase<QuizAttendance.Maintenance.MaintenanceSoap>, QuizAttendance.Maintenance.MaintenanceSoap {
        
        public MaintenanceSoapClient() {
        }
        
        public MaintenanceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaintenanceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaintenanceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaintenanceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.GetSchoolYearsResponse QuizAttendance.Maintenance.MaintenanceSoap.GetSchoolYears(QuizAttendance.Maintenance.GetSchoolYearsRequest request) {
            return base.Channel.GetSchoolYears(request);
        }
        
        public QuizAttendance.Maintenance.ArrayOfString GetSchoolYears() {
            QuizAttendance.Maintenance.GetSchoolYearsRequest inValue = new QuizAttendance.Maintenance.GetSchoolYearsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetSchoolYearsRequestBody();
            QuizAttendance.Maintenance.GetSchoolYearsResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetSchoolYears(inValue);
            return retVal.Body.GetSchoolYearsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSchoolYearsResponse> QuizAttendance.Maintenance.MaintenanceSoap.GetSchoolYearsAsync(QuizAttendance.Maintenance.GetSchoolYearsRequest request) {
            return base.Channel.GetSchoolYearsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSchoolYearsResponse> GetSchoolYearsAsync() {
            QuizAttendance.Maintenance.GetSchoolYearsRequest inValue = new QuizAttendance.Maintenance.GetSchoolYearsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetSchoolYearsRequestBody();
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetSchoolYearsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.GetSectionsResponse QuizAttendance.Maintenance.MaintenanceSoap.GetSections(QuizAttendance.Maintenance.GetSectionsRequest request) {
            return base.Channel.GetSections(request);
        }
        
        public QuizAttendance.Maintenance.ArrayOfString GetSections() {
            QuizAttendance.Maintenance.GetSectionsRequest inValue = new QuizAttendance.Maintenance.GetSectionsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetSectionsRequestBody();
            QuizAttendance.Maintenance.GetSectionsResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetSections(inValue);
            return retVal.Body.GetSectionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSectionsResponse> QuizAttendance.Maintenance.MaintenanceSoap.GetSectionsAsync(QuizAttendance.Maintenance.GetSectionsRequest request) {
            return base.Channel.GetSectionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSectionsResponse> GetSectionsAsync() {
            QuizAttendance.Maintenance.GetSectionsRequest inValue = new QuizAttendance.Maintenance.GetSectionsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetSectionsRequestBody();
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetSectionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.GetRoomsResponse QuizAttendance.Maintenance.MaintenanceSoap.GetRooms(QuizAttendance.Maintenance.GetRoomsRequest request) {
            return base.Channel.GetRooms(request);
        }
        
        public QuizAttendance.Maintenance.ArrayOfString GetRooms() {
            QuizAttendance.Maintenance.GetRoomsRequest inValue = new QuizAttendance.Maintenance.GetRoomsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetRoomsRequestBody();
            QuizAttendance.Maintenance.GetRoomsResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetRooms(inValue);
            return retVal.Body.GetRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetRoomsResponse> QuizAttendance.Maintenance.MaintenanceSoap.GetRoomsAsync(QuizAttendance.Maintenance.GetRoomsRequest request) {
            return base.Channel.GetRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetRoomsResponse> GetRoomsAsync() {
            QuizAttendance.Maintenance.GetRoomsRequest inValue = new QuizAttendance.Maintenance.GetRoomsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetRoomsRequestBody();
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.GetSubjectsResponse QuizAttendance.Maintenance.MaintenanceSoap.GetSubjects(QuizAttendance.Maintenance.GetSubjectsRequest request) {
            return base.Channel.GetSubjects(request);
        }
        
        public QuizAttendance.Maintenance.ArrayOfString GetSubjects() {
            QuizAttendance.Maintenance.GetSubjectsRequest inValue = new QuizAttendance.Maintenance.GetSubjectsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetSubjectsRequestBody();
            QuizAttendance.Maintenance.GetSubjectsResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetSubjects(inValue);
            return retVal.Body.GetSubjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSubjectsResponse> QuizAttendance.Maintenance.MaintenanceSoap.GetSubjectsAsync(QuizAttendance.Maintenance.GetSubjectsRequest request) {
            return base.Channel.GetSubjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetSubjectsResponse> GetSubjectsAsync() {
            QuizAttendance.Maintenance.GetSubjectsRequest inValue = new QuizAttendance.Maintenance.GetSubjectsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetSubjectsRequestBody();
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetSubjectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.GetStudentsResponse QuizAttendance.Maintenance.MaintenanceSoap.GetStudents(QuizAttendance.Maintenance.GetStudentsRequest request) {
            return base.Channel.GetStudents(request);
        }
        
        public QuizAttendance.Maintenance.Student[] GetStudents() {
            QuizAttendance.Maintenance.GetStudentsRequest inValue = new QuizAttendance.Maintenance.GetStudentsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetStudentsRequestBody();
            QuizAttendance.Maintenance.GetStudentsResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetStudents(inValue);
            return retVal.Body.GetStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetStudentsResponse> QuizAttendance.Maintenance.MaintenanceSoap.GetStudentsAsync(QuizAttendance.Maintenance.GetStudentsRequest request) {
            return base.Channel.GetStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetStudentsResponse> GetStudentsAsync() {
            QuizAttendance.Maintenance.GetStudentsRequest inValue = new QuizAttendance.Maintenance.GetStudentsRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetStudentsRequestBody();
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.InsertSchoolYearResponse QuizAttendance.Maintenance.MaintenanceSoap.InsertSchoolYear(QuizAttendance.Maintenance.InsertSchoolYearRequest request) {
            return base.Channel.InsertSchoolYear(request);
        }
        
        public void InsertSchoolYear(string SY) {
            QuizAttendance.Maintenance.InsertSchoolYearRequest inValue = new QuizAttendance.Maintenance.InsertSchoolYearRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertSchoolYearRequestBody();
            inValue.Body.SY = SY;
            QuizAttendance.Maintenance.InsertSchoolYearResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertSchoolYear(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSchoolYearResponse> QuizAttendance.Maintenance.MaintenanceSoap.InsertSchoolYearAsync(QuizAttendance.Maintenance.InsertSchoolYearRequest request) {
            return base.Channel.InsertSchoolYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSchoolYearResponse> InsertSchoolYearAsync(string SY) {
            QuizAttendance.Maintenance.InsertSchoolYearRequest inValue = new QuizAttendance.Maintenance.InsertSchoolYearRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertSchoolYearRequestBody();
            inValue.Body.SY = SY;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertSchoolYearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.InsertRoomResponse QuizAttendance.Maintenance.MaintenanceSoap.InsertRoom(QuizAttendance.Maintenance.InsertRoomRequest request) {
            return base.Channel.InsertRoom(request);
        }
        
        public void InsertRoom(string R) {
            QuizAttendance.Maintenance.InsertRoomRequest inValue = new QuizAttendance.Maintenance.InsertRoomRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertRoomRequestBody();
            inValue.Body.R = R;
            QuizAttendance.Maintenance.InsertRoomResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertRoomResponse> QuizAttendance.Maintenance.MaintenanceSoap.InsertRoomAsync(QuizAttendance.Maintenance.InsertRoomRequest request) {
            return base.Channel.InsertRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertRoomResponse> InsertRoomAsync(string R) {
            QuizAttendance.Maintenance.InsertRoomRequest inValue = new QuizAttendance.Maintenance.InsertRoomRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertRoomRequestBody();
            inValue.Body.R = R;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.InsertSectionResponse QuizAttendance.Maintenance.MaintenanceSoap.InsertSection(QuizAttendance.Maintenance.InsertSectionRequest request) {
            return base.Channel.InsertSection(request);
        }
        
        public void InsertSection(string Sec) {
            QuizAttendance.Maintenance.InsertSectionRequest inValue = new QuizAttendance.Maintenance.InsertSectionRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertSectionRequestBody();
            inValue.Body.Sec = Sec;
            QuizAttendance.Maintenance.InsertSectionResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertSection(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSectionResponse> QuizAttendance.Maintenance.MaintenanceSoap.InsertSectionAsync(QuizAttendance.Maintenance.InsertSectionRequest request) {
            return base.Channel.InsertSectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSectionResponse> InsertSectionAsync(string Sec) {
            QuizAttendance.Maintenance.InsertSectionRequest inValue = new QuizAttendance.Maintenance.InsertSectionRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertSectionRequestBody();
            inValue.Body.Sec = Sec;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertSectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.InsertSubjectResponse QuizAttendance.Maintenance.MaintenanceSoap.InsertSubject(QuizAttendance.Maintenance.InsertSubjectRequest request) {
            return base.Channel.InsertSubject(request);
        }
        
        public void InsertSubject(string Sub) {
            QuizAttendance.Maintenance.InsertSubjectRequest inValue = new QuizAttendance.Maintenance.InsertSubjectRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertSubjectRequestBody();
            inValue.Body.Sub = Sub;
            QuizAttendance.Maintenance.InsertSubjectResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertSubject(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSubjectResponse> QuizAttendance.Maintenance.MaintenanceSoap.InsertSubjectAsync(QuizAttendance.Maintenance.InsertSubjectRequest request) {
            return base.Channel.InsertSubjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertSubjectResponse> InsertSubjectAsync(string Sub) {
            QuizAttendance.Maintenance.InsertSubjectRequest inValue = new QuizAttendance.Maintenance.InsertSubjectRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertSubjectRequestBody();
            inValue.Body.Sub = Sub;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertSubjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.InsertStudentResponse QuizAttendance.Maintenance.MaintenanceSoap.InsertStudent(QuizAttendance.Maintenance.InsertStudentRequest request) {
            return base.Channel.InsertStudent(request);
        }
        
        public void InsertStudent(string LName, string GName, string MInitial, string StudNum) {
            QuizAttendance.Maintenance.InsertStudentRequest inValue = new QuizAttendance.Maintenance.InsertStudentRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertStudentRequestBody();
            inValue.Body.LName = LName;
            inValue.Body.GName = GName;
            inValue.Body.MInitial = MInitial;
            inValue.Body.StudNum = StudNum;
            QuizAttendance.Maintenance.InsertStudentResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertStudent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertStudentResponse> QuizAttendance.Maintenance.MaintenanceSoap.InsertStudentAsync(QuizAttendance.Maintenance.InsertStudentRequest request) {
            return base.Channel.InsertStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.InsertStudentResponse> InsertStudentAsync(string LName, string GName, string MInitial, string StudNum) {
            QuizAttendance.Maintenance.InsertStudentRequest inValue = new QuizAttendance.Maintenance.InsertStudentRequest();
            inValue.Body = new QuizAttendance.Maintenance.InsertStudentRequestBody();
            inValue.Body.LName = LName;
            inValue.Body.GName = GName;
            inValue.Body.MInitial = MInitial;
            inValue.Body.StudNum = StudNum;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).InsertStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.DeleteSubjectResponse QuizAttendance.Maintenance.MaintenanceSoap.DeleteSubject(QuizAttendance.Maintenance.DeleteSubjectRequest request) {
            return base.Channel.DeleteSubject(request);
        }
        
        public void DeleteSubject(string Sub) {
            QuizAttendance.Maintenance.DeleteSubjectRequest inValue = new QuizAttendance.Maintenance.DeleteSubjectRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteSubjectRequestBody();
            inValue.Body.Sub = Sub;
            QuizAttendance.Maintenance.DeleteSubjectResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteSubject(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSubjectResponse> QuizAttendance.Maintenance.MaintenanceSoap.DeleteSubjectAsync(QuizAttendance.Maintenance.DeleteSubjectRequest request) {
            return base.Channel.DeleteSubjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSubjectResponse> DeleteSubjectAsync(string Sub) {
            QuizAttendance.Maintenance.DeleteSubjectRequest inValue = new QuizAttendance.Maintenance.DeleteSubjectRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteSubjectRequestBody();
            inValue.Body.Sub = Sub;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteSubjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.DeleteSectionResponse QuizAttendance.Maintenance.MaintenanceSoap.DeleteSection(QuizAttendance.Maintenance.DeleteSectionRequest request) {
            return base.Channel.DeleteSection(request);
        }
        
        public void DeleteSection(string Sec) {
            QuizAttendance.Maintenance.DeleteSectionRequest inValue = new QuizAttendance.Maintenance.DeleteSectionRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteSectionRequestBody();
            inValue.Body.Sec = Sec;
            QuizAttendance.Maintenance.DeleteSectionResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteSection(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSectionResponse> QuizAttendance.Maintenance.MaintenanceSoap.DeleteSectionAsync(QuizAttendance.Maintenance.DeleteSectionRequest request) {
            return base.Channel.DeleteSectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSectionResponse> DeleteSectionAsync(string Sec) {
            QuizAttendance.Maintenance.DeleteSectionRequest inValue = new QuizAttendance.Maintenance.DeleteSectionRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteSectionRequestBody();
            inValue.Body.Sec = Sec;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteSectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.DeleteRoomResponse QuizAttendance.Maintenance.MaintenanceSoap.DeleteRoom(QuizAttendance.Maintenance.DeleteRoomRequest request) {
            return base.Channel.DeleteRoom(request);
        }
        
        public void DeleteRoom(string R) {
            QuizAttendance.Maintenance.DeleteRoomRequest inValue = new QuizAttendance.Maintenance.DeleteRoomRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteRoomRequestBody();
            inValue.Body.R = R;
            QuizAttendance.Maintenance.DeleteRoomResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteRoomResponse> QuizAttendance.Maintenance.MaintenanceSoap.DeleteRoomAsync(QuizAttendance.Maintenance.DeleteRoomRequest request) {
            return base.Channel.DeleteRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteRoomResponse> DeleteRoomAsync(string R) {
            QuizAttendance.Maintenance.DeleteRoomRequest inValue = new QuizAttendance.Maintenance.DeleteRoomRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteRoomRequestBody();
            inValue.Body.R = R;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.DeleteSchoolYearResponse QuizAttendance.Maintenance.MaintenanceSoap.DeleteSchoolYear(QuizAttendance.Maintenance.DeleteSchoolYearRequest request) {
            return base.Channel.DeleteSchoolYear(request);
        }
        
        public void DeleteSchoolYear(string SY) {
            QuizAttendance.Maintenance.DeleteSchoolYearRequest inValue = new QuizAttendance.Maintenance.DeleteSchoolYearRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteSchoolYearRequestBody();
            inValue.Body.SY = SY;
            QuizAttendance.Maintenance.DeleteSchoolYearResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteSchoolYear(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSchoolYearResponse> QuizAttendance.Maintenance.MaintenanceSoap.DeleteSchoolYearAsync(QuizAttendance.Maintenance.DeleteSchoolYearRequest request) {
            return base.Channel.DeleteSchoolYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.DeleteSchoolYearResponse> DeleteSchoolYearAsync(string SY) {
            QuizAttendance.Maintenance.DeleteSchoolYearRequest inValue = new QuizAttendance.Maintenance.DeleteSchoolYearRequest();
            inValue.Body = new QuizAttendance.Maintenance.DeleteSchoolYearRequestBody();
            inValue.Body.SY = SY;
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).DeleteSchoolYearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuizAttendance.Maintenance.GetClassRecordResponse QuizAttendance.Maintenance.MaintenanceSoap.GetClassRecord(QuizAttendance.Maintenance.GetClassRecordRequest request) {
            return base.Channel.GetClassRecord(request);
        }
        
        public QuizAttendance.Maintenance.Class[] GetClassRecord() {
            QuizAttendance.Maintenance.GetClassRecordRequest inValue = new QuizAttendance.Maintenance.GetClassRecordRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetClassRecordRequestBody();
            QuizAttendance.Maintenance.GetClassRecordResponse retVal = ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetClassRecord(inValue);
            return retVal.Body.GetClassRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetClassRecordResponse> QuizAttendance.Maintenance.MaintenanceSoap.GetClassRecordAsync(QuizAttendance.Maintenance.GetClassRecordRequest request) {
            return base.Channel.GetClassRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuizAttendance.Maintenance.GetClassRecordResponse> GetClassRecordAsync() {
            QuizAttendance.Maintenance.GetClassRecordRequest inValue = new QuizAttendance.Maintenance.GetClassRecordRequest();
            inValue.Body = new QuizAttendance.Maintenance.GetClassRecordRequestBody();
            return ((QuizAttendance.Maintenance.MaintenanceSoap)(this)).GetClassRecordAsync(inValue);
        }
    }
}
